### PR TITLE
cmake, ci: updates for recent nixpkgs

### PR DESCRIPTION
**Pull request by ryanofsky**
This PR fixes two problems that happen with recent nixpkgs. The first commit works around compilation errors that happen when IWYU is enabled with (`-DMP_ENABLE_IWYU=ON`) that were caused by https://github.com/NixOS/nixpkgs/pull/445095. The second commit fixes problems building old versions of Cap'n Proto with CMake 4.0 in shell.nix.

Neither problem has showed up so far running in github actions, only running locally with unstable nixpkgs. More details about the problems and fixes are in the commit messages.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK b66a6d35526f69a9f3cdb39e2cd85480732555ee, I have reviewed the code and it looks OK.

**Review by sedited — APPROVED** [review]
ACK db7acb3ce279196607fd628126c58588ba582483

**Review by hebasto — APPROVED** [review]
re-ACK db7acb3ce279196607fd628126c58588ba582483.

File: CMakeLists.txt [hunk 1]
```diff
@@ -111,6 +104,15 @@ if(MP_ENABLE_IWYU)
   endif()
 endif()
 
+if(MP_ENABLE_CLANG_TIDY OR MP_ENABLE_IWYU)
+  # Workaround for nix from https://gitlab.kitware.com/cmake/cmake/-/issues/20912#note_793338
+  # Nix injects header paths via $NIX_CFLAGS_COMPILE; CMake tags these as
+  # CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES and omits them from the compile
+  # database, so clang-tidy, which ignores $NIX_CFLAGS_COMPILE, can't find capnp
+  # headers. Setting them as standard passes them to clang-tidy.
+  set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
```
Comment (ryanofsky) [inline CMakeLists.txt:113]: In commit "cmake: Fix IWYU in nix by adding CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES" (91a7759a9abe4700d466adb94024dce81fa230ab)

Note: I might merge this PR anyway since it has two acks, but this comment isn't exactly right since newer versions of clang-tidy in nixpkgs fix the issue and make this workaround unnecessary. The fix was https://github.com/NixOS/nixpkgs/commit/d46fa2640e3d3f05b4da137be9b4f016cf043c37 (https://github.com/NixOS/nixpkgs/pull/462747).

The problem with IWYU [still exists](https://github.com/NixOS/nixpkgs/blob/dad2d8b535b29c0949b25fcc3bdbcced80e03f0c/pkgs/development/tools/analysis/include-what-you-use/wrapper#L7) but can be fixed with a similar change, which should probably be a PR:

```diff
--- a/pkgs/development/tools/analysis/include-what-you-use/wrapper
+++ b/pkgs/development/tools/analysis/include-what-you-use/wrapper
@@ -4,7 +4,7 @@ buildcpath() {
   local path after
   while (( $# )); do
     case $1 in
-        -isystem)
+        -isystem|-cxx-isystem)
             shift
             path=$path${path:+':'}$1
             ;;
```
